### PR TITLE
Update external libraries' versions in .classpath #762

### LINKED ISSUE #762: Update .classpath to be compatible with new libraries
Some changes to code may also be desirable as the new setting results in several more warnings.

### PR DESCRIPTION
**Pull request by ndt93**
Resolves #762

### CODE REVIEW

**Comment by lejolly** [comment]
Looks ok to me, @HyungJon can you confirm that it works for you?

**Comment by HyungJon** [comment]
Can I know how I can pull this specific branch to my local machine, preferably without using GitHub for Windows?

**Comment by lejolly** [comment]
add it as a new remote `git remote add ndt93 https://github.com/ndt93/HubTurbo.git`
then just checkout the appropriate branch

**Comment by HyungJon** [comment]
Yes, it looks like this is free from the problem I was having (gradlew build skipping all tests and declaring them passed).

**Comment by lejolly** [comment]
Ok, will mark as to merge.

**Pull request merged**
