### PR TITLE
"Change labels (L)" option doesn't appear in the context menu for an issue sometimes #1383

### LINKED ISSUE #1383: "Change labels (L)" option doesn't appear in the context menu for an issue sometimes

### PR DESCRIPTION
**Pull request by raisfathin**
Fixes #1383

### CODE REVIEW

**Comment by dariusf** [comment]
Nice catch.

**Comment by raisfathin** [comment]
@dariusf I can't merge this due to coverage drop (and the class that has coverage drop is unrelated to this PR, I think). Should I add tests?

**Comment by dariusf** [comment]
Nope, that can be done in a separate issue. I'll help to merge.

**Comment by raisfathin** [comment]
Thanks!

**Pull request merged**
