### PR TITLE
Rephrase status message for label change #1196

### LINKED ISSUE #1196: Rephrase status message for label change
image

Shouldn't this read something like `Labels changed for #nnnn` `undo` ?

### PR DESCRIPTION
**Pull request by whattokingu**
Fixes #1196

### CODE REVIEW

**Comment by dariusf** [comment]
Thanks!

Small issue: the PR description should have "fixes x" to [automatically close the issue](https://github.com/blog/1506-closing-issues-via-pull-requests).

**Comment by whattokingu** [comment]
Alright. Will take note next time. Changed!

**Comment by damithc** [comment]
Still not correct. Read the instructions carefully. See other PRs for an example.

**Comment by damithc** [comment]
The format of the PR description (i.e. the first title) is still not correct.

**Pull request merged**
