### PR TITLE
repo picker: clicked repo is not switched to #1464

### LINKED ISSUE #1464: repo picker: clicked repo is not switched to
If I click a repo name and press 'confirm', the default repo doesn't change to the chosen repo. I think we had the same bug in the label picker or the milestone picker (don't remember which one)

### PR DESCRIPTION
**Pull request by raisfathin**
Fixes #1464

### CODE REVIEW

**Comment by damithc** [comment]
@raisfathin assign the same person who reviewed the repo picker PR.

**Comment by raisfathin** [comment]
Done.

**Comment by ndt93** [comment]
Looks good. I suppose the new tests should cover any similar regressions?

Also, there are conflicts with the master so you can try to resolve that first.

**Comment by raisfathin** [comment]
Yep. Ok, just rebased.

**Comment by raisfathin** [comment]
Ready for another review!

**Pull request merged**
