### PR TITLE
milestone missing from some issues #1054

### LINKED ISSUE #1054: milestone missing from some issues
This happens for teammates (has a lot of milestones), so it could be a pagination issue
image

### PR DESCRIPTION
**Pull request by ndt93**
Fixes #1054

### CODE REVIEW

**Comment by ndt93** [comment]
After running a version with this fix, a cache refresh is also required for it to take effect.

**Comment by ndt93** [comment]
@dariusf Can help review this? This bug is quite dangerous.

**Comment by dariusf** [comment]
I get that the bug was caused by the same object being used twice, but why does it happen? Does the request fail if the object has already been mutated with some result?

If `request` is only needed lower down, maybe move it inside the else branch?

**Comment by ndt93** [comment]
Yup, the header request mutates the `request` object and the `PageIterator` can only carry on from the page at which the header request left off. I will move it to the else branch.

**Comment by ndt93** [comment]
@dariusf I've refactored nested `if/else` in `getUpdatedItems` also. You can check this again.

**Comment by dariusf** [comment]
Okay, looks good.

**Pull request merged**
