### PR TITLE
A flood of refresh triggered after computer is awaken from sleep/hibernation #369

### LINKED ISSUE #369: A flood of refresh triggered after computer is awaken from sleep/hibernation
It also causes spike in memory usage. #282

### PR DESCRIPTION
**Pull request by taychunmei**
Fixes #369

### CODE REVIEW

**Comment by damithc** [comment]
Does it solve the problem?

**Comment by taychunmei** [comment]
I tested with my computer. It seemed to work

**Comment by damithc** [comment]
@dariusf for review

**Comment by dariusf** [comment]
fixedRate will run tasks at a constant rate, no matter how long the tasks take to finish.

fixedDelay will wait till a task finishes, then schedule the next one from that point.

I'm not sure that this addresses this exact issue (wasn't it fixed with the change from timer to thread pool?), but fixedDelay is the one we want.

**Comment by damithc** [comment]
How big is the thread pool?
Also consider the behavior when the connection to the server is not
available. The network connection may not be available for a short while
soon after the computer wakes up, which might cause this kind of problems.

**Comment by dariusf** [comment]
It's 1 large. It's just meant to run the periodic update over and over. The reason for changing it was that the executor classes are more robust than Timer.

This shouldn't be affected by network issues. If the network is available it just doesn't update on that tick now.

**Pull request merged**
