### PR TITLE
Tips panel in the Sample Board

### LINKED ISSUE #1331: Tips panel in the Sample Repo
Would require the creation of a tips repository!

### PR DESCRIPTION
**Pull request by codemanmeet**
Fixes #1331

### CODE REVIEW

**Comment by codemanmeet** [comment]
[codemanmeet/TipsRepo](https://github.com/codemanmeet/TipsRepo/issues)

**Comment by damithc** [comment]
Why `Useful Tips!` are associated with a label called `latest-tips`?
Why there is an exclamation mark at the end of the panel name?
Is the panel created automatically for new users or created on demand?

**Comment by codemanmeet** [comment]
Actually, yup! We can call it `Latest tips` itself. The panel is the first panel included in the `Sample Board` which is opened up for first time users as well as available on demand in the Boards -> Auto-create -> Sample Board menu option.I have removed `HubTurbo/HubTurbo` from the sample repos that are loaded on startup for first time users since it is huge and requires time to be downloaded.

**Comment by codemanmeet** [comment]
@damithc @dariusf ready for review!

**Comment by dariusf** [comment]
No comments on the code changes. I think some tips can be written less like user stories though. :stuck_out_tongue: Just in a more friendly way. The tone of 3 or 4 is good.

**Comment by codemanmeet** [comment]
Sure, I will edit some of the tips to be more to-the-point! As for the tests, no new tests are required. The new constants are declared in `BoardAutoCreator.java` and assigned appropriately in a `final Map`. The `final Map` is called in all tests so nothing changes in the tests at all! -:)

**Pull request merged**
