### PR TITLE
Add a generic way to traverse context menus in tests #1314

### LINKED ISSUE #1314: Add a generic way to traverse context menus in tests
We have `traverseMenu`, which takes a menu path (as a list of strings) and clicks the trigger. We can do the same for context menus, which might allow us to move some tests (for example, `ContextMenuUnstableTests`) out of `unstable`.

### PR DESCRIPTION
**Pull request by raisfathin**

### CODE REVIEW

**Comment by raisfathin** [comment]
Ready for review!

**Comment by dariusf** [comment]
Nice work. Could we try and share even more code between `traverseHubTurboMenu` and `traverseContextMenu`? We can pull out the parts which require just a `List<? extends MenuItem>` (`Menu` is a subtype of `MenuItem`).

**Comment by raisfathin** [comment]
Sure! I forgot Java has this `? extends Base` feature. It makes the code nicer as well.

**Comment by dariusf** [comment]
Do put `fixes #x` in the description, otherwise the related issue won't close upon merge.

**Comment by raisfathin** [comment]
Oops, sorry, thought I had put it already :disappointed:

**Pull request merged**
