### PR TITLE
Hotkey for closing an issue should be consistent with the context menu option #1430

### LINKED ISSUE #1430: Hotkey for closing an issue should be consistent with the context menu option
Currently, 'X' is used to close an issue using even though the context menu indicates 'Close issue (C)'.

### PR DESCRIPTION
**Pull request by yl-coder**
Fixes #1430

### CODE REVIEW

**Comment by m133225** [comment]
I think we should be changing the context menu option to `X` rather than changing the hotkey. This was discussed in #1296 .

**Comment by yl-coder** [comment]
Ok, I have change the context menu to X.

Ready for review.

**Comment by damithc** [comment]
@yl-coder the branch now has some merge conflicts

**Comment by yl-coder** [comment]
Merge conflicts resolved

Ready for review

**Comment by ndt93** [comment]
@HansNewbie Hey Hans, can help review this?

**Comment by HansNewbie** [comment]
Good to merge. Docs seems to have been updated before this PR.

**Pull request merged**
