### PR TITLE
Add separator for existing labels in label picker #875

### LINKED ISSUE #875: Add separator for existing labels in label picker
probably just a `|` or something

### PR DESCRIPTION
**Pull request by lejolly**
Fixes #875

edit_labels_for_issue__10_in_dummy_dummy

### CODE REVIEW

**Comment by damithc** [comment]
Ready to review?

**Comment by lejolly** [comment]
Yup.

**Comment by damithc** [comment]
Go ahead and assign Darius or Dat as the reviewer Joshua.

**Comment by acruis** [comment]
Ok, looks good.

**Pull request merged**
