### PR TITLE
Bring browser window to the front and keep it in focus #240

### LINKED ISSUE #240: Bring browser window to the front and keep it in focus
Currently we can't find a way to do this using Selenium.

### LINKED ISSUE #267: Ctrl+I should shift focus to Browser
The next logical action is to type the issue title, so the focus should go to the Browser automatically.

### PR DESCRIPTION
**Pull request by rd1992**
Fixes #240, fixes #267

### CODE REVIEW

**Comment by dariusf** [comment]
I've reviewed the changes, looks good. Small issue: we could make New Label/Milestone bring the window into focus as well?

Apart from that I can merge whenever.

**Comment by rd1992** [comment]
@dariusf ohh yes good point. have added that functionality. you can merge it now

**Comment by dariusf** [comment]
Alright, push to this branch when you're done.

**Comment by rd1992** [comment]
done :)

**Pull request merged**
