### PR TITLE
Switching project quickly causes wrong data to be written to cache #379

### LINKED ISSUE #379: Switching project quickly causes wrong data to be written to cache

### LINKED ISSUE #380: Refactoring in preparation for future fixes
Groundwork for a number of concurrency- and memory-related issues. Won't completely fix but slightly improves the situation for #276, #379, #282.

- Reduced maximum memory usage and startup time.
- Code is simpler and less brittle. Fewer complications from data binding.
- #379 happens much less frequently.

### LINKED ISSUE #392: Issues of one project shown under another project
See below. Happened during project switching.

image

### PR DESCRIPTION
**Pull request by dariusf**
Fixes #379, fixes #392, fixes #380.

- Finally managed to synchronise data updates
- Minor refactoring and testing
- Removed more unnecessary observables
- Reduced number of UI updates required per data update by more than half

Overall startup and repo switching should be faster.

### CODE REVIEW

**Comment by damithc** [comment]
Go ahead, merge, and you can even release. Sooner we release, sooner it gets tested :-)

**Comment by dariusf** [comment]
Okay, uploading a new version now.

**Comment by dariusf** [comment]
For some reason the upload is taking really long... It should hopefully be done by tonight.

**Comment by dariusf** [comment]
Still can't upload. I'll keep trying tomorrow.

**Pull request merged**
