### PR TITLE
Wrong Chrome window brought to front #450

### LINKED ISSUE #450: Wrong Chrome window brought to front
In my Win8 computer, I had another Chrome window. HT brings that window to the front instead of the one spawned by HT.

### PR DESCRIPTION
**Pull request by rd1992**
Fixes #450

### CODE REVIEW

**Comment by damithc** [comment]
@dariusf release a new version with this if this fix is ok.

**Comment by dariusf** [comment]
It looks okay to me. Should we include all the currently-open PRs in the new version as well? They're all more or less standalone.

**Comment by damithc** [comment]
No. For this release, merge this one only.
In future, this is what we should do between a dev release and the public
release of the same: we keep adding new features to the master. Any fixes
to the dev release should be done in a separate branch (e.g. V1.9-hotfixes)
branching off from the dev release commit. That way, we fix the dev release
without bringing in new features to the next public release. hot fix branch
should merge to master frequently so that the current master contains both
fixes to dev release and new features for future releases. If not clear, we
can discuss next time we meet.

**Comment by dariusf** [comment]
Okay, I'll merge only this one. Not exactly sure of the branching workflow but I'll clarify next week.

**Pull request merged**
