### PR TITLE
 Correct variable name to pass checkstyle in DummyRepoState #1366

### LINKED ISSUE #1366: Correct variable name to pass checkstyle in DummyRepoState
In `DummyRepoState`, a variable name `noOfDummyIssues` violates checkstyle because it is a constant but not using all capital letters.

### PR DESCRIPTION
**Pull request by antimatterx**
Fixes #1366. Changed a constant name from noOfDummyIssues to NO_OF_DUMMY_ISSUES, to conform to coding standards.

### CODE REVIEW

**Comment by ndt93** [comment]
@antimatterx Is this ready for review? Also the PR title convention needs a `#<IssueNumber>` at the end.

**Comment by antimatterx** [comment]
@ndt93 yup it's ready for review.  And noted about the PR title convention.

**Comment by ndt93** [comment]
@acruis Can help review this? Thanks.

**Comment by acruis** [comment]
A pull request's title should be exactly the same as the original issue title. Also, do include a "Fixes #1366" in the pull request description, so as to create a reference to the original issue, as per [`process.md`](https://github.com/HubTurbo/HubTurbo/blob/master/docs/process.md#fixing-issues).

No other problems, but it appears that the branch is behind `master`. Do pull from `master` and fix the conflicts :)

**Comment by antimatterx** [comment]
Hi, I've fixed the merge conflicts and title.

**Comment by acruis** [comment]
No more comments from me.

**Pull request merged**
