### PR TITLE
Updater - Merging to master

### PR DESCRIPTION
**Pull request by HansNewbie**
Issues #1229 #1230 #1271 have been done in updater branch. Requesting to merge updater branch to master branch.

### CODE REVIEW

**Comment by HansNewbie** [comment]
@dariusf ready for review. Basically this is just merging the updater branch to the master branch. I have cleaned up the commits to reflect each issue, with another commit that basically cleans up things so that it is ready for deployment.

**Comment by dariusf** [comment]
Only looked at the last commit. I would personally split the changes unrelated to transitioning from `updater` to `master` into other commits, but it's not a big deal.

Looks good otherwise. Needs a rebase, so coveralls can run. Does this mean we can use this for the release tomorrow? :sweat_smile:

**Comment by HansNewbie** [comment]
I can rename the commit just to reflect the other changes.  I did rebase, not sure why the coveralls don't run.

If we include this in release tomorrow, then the auto-update will start next week since only those using the version release tomorrow have the auto-update functionality. Maybe next next week since we release to public only next week?

**Comment by HansNewbie** [comment]
I just did another rebase and it seems the coveralls is not run. Did I do something wrong?

**Comment by HansNewbie** [comment]
Will open a new PR to trigger coverall.

**Comment by HansNewbie** [comment]
Ready for review.

**Pull request merged**
