### PR TITLE
Fix error message for when the board name is too long #1223

### LINKED ISSUE #1223: Fix error message for when the board name is too long
screen shot 2016-01-31 at 12 02 09 pm

It does not correctly format the number of characters in the message.

### PR DESCRIPTION
**Pull request by HyungJon**
Fixes #1223

### CODE REVIEW

**Comment by damithc** [comment]
PR name is missing the corresponding issue number.

**Comment by HyungJon** [comment]
Right, fixed.

**Comment by damithc** [comment]
You know what to do when ready for review :-)

**Comment by HyungJon** [comment]
Hmm something seemed wrong with the CI build and I couldn't access the details, so I just reopened it. Now Travis does pass. I think I should add a test though.
I seem to have forgotten a lot of the workflow in these 2 months, what was the next step again? '^'

**Comment by damithc** [comment]
Refer https://github.com/HubTurbo/HubTurbo/blob/master/docs/process.md

**Comment by dariusf** [comment]
I don't think a test is necessary for this. We can't check every single part of the UI.

**Pull request merged**
