### PR TITLE
Change the color of closed issue cards to light red #1426

### LINKED ISSUE #1426: Change the color of closed issue cards to light red
Perhaps we should use light red to be consistent with GitHub color scheme?

image

### PR DESCRIPTION
**Pull request by yl-coder**
Fixes #1426 

image

### CODE REVIEW

**Comment by damithc** [comment]
Can make it lighter? Like the shade of red used in github diff view to show removed lines?

**Comment by yl-coder** [comment]
Ok. Changed.

image

**Comment by yl-coder** [comment]
Ready for review

**Comment by damithc** [comment]
Better. I don't mind going a bit more lighter just to see how it is.

**Comment by yl-coder** [comment]
image

**Comment by damithc** [comment]
OK, let's go with that.

**Comment by ndt93** [comment]
@HansNewbie And this.

**Comment by HansNewbie** [comment]
Good to merge.

**Pull request merged**
