### PR TITLE
Typo in boards.md #931

### LINKED ISSUE #931: Typo in boards.md
image

### PR DESCRIPTION
**Pull request by HyungJon**
Fixes #931

### CODE REVIEW

**Comment by dariusf** [comment]
You can merge, now that you're no longer working off a fork. Just follow the merge commit naming convention.

**Comment by HyungJon** [comment]
Okay. Just to check, is the command "git merge -m <merge commit> <commit>" from master branch, then push?

**Comment by dariusf** [comment]
That should work. (commit) would be the branch name.

**Comment by HyungJon** [comment]
Uhh, is this what's supposed to happen?

**Comment by dariusf** [comment]
That's because the first commit was merged, rather than the HEAD of this branch (the merge from master). GitHub doesn't know that the change was integrated.

**Comment by HyungJon** [comment]
I see. Should I have merged the commit 9f01d56 instead of the branch then? I guess it wouldn't cause problems if I merge it on top of the first commit?

**Comment by dariusf** [comment]
I suppose it's fine, since there were no conflicts and the relevant changes made it into master. We'll just manually close this and the issue. In future just refer to the branch via its name, rather than some commit on it.
```sh
git checkout master
git merge origin/Issue931 -m "[931] Typo in boards.md"
```

**Comment by HyungJon** [comment]
Ah I didn't add the origin/ there. Noted.

**Comment by dariusf** [comment]
Well, using `Issue931` would have merged 9f01d56 as well assuming it was what you pushed to `origin/Issue931`, so either one would have been correct. I'm not sure why the first commit went in. :confused: Did you reset your local branch after pushing?

**Comment by HyungJon** [comment]
Oh, then it's because I merged master into the branch with the update branch button on GitHub, then forgot to pull to local before merging it. Apologies there.

Speaking of which, is the update button discouraged like merging PR to master on GitHub? Or is the latter discouraged to use merge messages?

**Comment by dariusf** [comment]
Yes, the latter is discouraged for that reason. Updating the branch via GitHub is no more convenient than merging locally (merge then pull vs merge then push), so it doesn't seem very useful.

**Pull request closed without merging**
