### PR TITLE
 Improve or change panel element selection in tests #933 

### LINKED ISSUE #933: Improve or change panel element selection in tests
Node IDs are unreliable and immutable.

Alternative solution proposed today: add ```get``` method for each element that allows tests to select elements through ```PanelControl``` -> ```FilterPanel``` at index -> element.

This will need some way for tests to access ```PanelControl``` or ```UI``` directly.

### PR DESCRIPTION
**Pull request by HyungJon**
Fixes #933 

Those tests involving more than 1 panels, especially if the ordering of the panels may change, were changed to use ```TextController``` to directly access panels instead of using IDs which are more fallible.

### CODE REVIEW

**Comment by HyungJon** [comment]
That... is strange. An unrelated ```BoardSwitchTest``` fails on Travis. Passes locally. I see no reason why this should be unstable though.

**Comment by HyungJon** [comment]
I found something I want to improve on. ```PanelsTest``` has a part where the two panels are swapped, but I found that they don't actually get swapped, at least most of the time. I'm going to add a test here now that we can directly access panels based on their indices, but I need to solve this UI issue first. The panel swapping seems kind of blocky, needs some retries until I can actually swap. Can panel swapping be improved?

**Comment by dariusf** [comment]
We could put in a hotkey to swap panels. The mouse event has always been unreliable.

**Comment by HyungJon** [comment]
Will do that in a separate issue then, and focus on the panel selection here.

As for ```BoardSwitchTest``` failing, I think it's Travis problem again. It only fails on Travis, and It's using the name "Dummy Board" instead of the assigned "Board 1" and such. I had similar issues before with Travis checking panel names with strange names like "Panel should have name quit", possibly some variables that somehow drifted in. Should this be considered an unstable test?

**Comment by dariusf** [comment]
What do you mean by Travis using a different name?

Tests can be nondeterministic in that sometimes nodes can't be found, key events fail or repeat many times, etc. but variables 'drifting in' sounds like a problem with the logic of the test or related setup, e.g. wrong node id causing a field to have a different name than expected.

If the field has a different value because of the aforementioned nondeterminism (and we need to pinpoint the cause), I suppose we could make this unstable, but not unless.

**Comment by HyungJon** [comment]
I've been looking into this more, I think it might be there's something wrong with how ```BoardSwitchTest``` is initiated. Possibly because of "testPrefs = new Preferences(true)"? It doesn't explain why this test is failing as a result of panel elements selection, but anyway something might be altering the starting state of ```Preferences```. Could you have a look at the problematic test?

As for the "drifting", I really have no idea. I had that problem once, where the name of the panel was something that's not supposed to be possible since there's no board with such a name.

**Comment by HyungJon** [comment]
Found the cause.

**Comment by HyungJon** [comment]
Right, solved.

**Comment by HyungJon** [comment]
@dariusf Can I have a review? Also can the fall in coverage be considered a false positive? I'm quite sure the panel element getter methods are responsible.

**Comment by dariusf** [comment]
I won't be able to get to this for a while. @lejolly could you help to review?

**Comment by lejolly** [comment]
looks ok, how does this fare on travis? namely, what's the pass/fail ratio?

**Comment by HyungJon** [comment]
Normally passes. I don't think I've seen it fail after I figured out what was causing the problem.

**Comment by lejolly** [comment]
could you run it for at least 10 tries and report how many times it fails?

**Comment by HyungJon** [comment]
@lejolly  Ran at least 10 times I think, passed every time.

**Comment by lejolly** [comment]
ok, could you try moving `PanelsTest` out of `unstable` and run it on travis a few times to see if it passes too?

**Comment by HyungJon** [comment]
Alright. I think I ran 3~4 times. All passed.

**Comment by lejolly** [comment]
ok, @dariusf good enough to move it back to the stable tests?

**Comment by dariusf** [comment]
Sure, should be fine.

**Comment by lejolly** [comment]
ok, looks good then.

**Pull request merged**
