### PR TITLE
Remove board: 'non removable' should be shown for each non-removable repo #1063

### LINKED ISSUE #1063: Remove board: 'non removable' should be shown for each non-removable repo
Currently it is shown as an item by itself. It is more intuitive to show it against each non-removable repo. 
e.g. `teammates\tepo [in use, not removable]`

### PR DESCRIPTION
**Pull request by HansNewbie**
Fixes #1063

### CODE REVIEW

**Comment by HansNewbie** [comment]
screen shot
@damithc is this good? I am not sure if the letter cases are ok.

**Comment by damithc** [comment]
Yup, looks good.

**Comment by HansNewbie** [comment]
@lejolly Can help me review this? Related to the previous issue you reviewed, just changed some UI. The PR passes locally; I rebuilt Travis because it failed the coverage.

**Comment by lejolly** [comment]
Looks good.

**Comment by HansNewbie** [comment]
Just to justify the coverage decrease: I deleted 3 lines, and so at the same time the coverage for the file drops by 3 lines. Will merge now.

**Pull request merged**
