### PR TITLE
Change milestone alias test in FilterLexerTests #1149

### LINKED ISSUE #1149: Change milestone alias test in FilterLexerTests
It tests `milestone:prev-1` and `milestone:next+1` which should be changed to `curr-1` and `curr+1`. The test was created since `+` was parsed wrongly before introduction of milestone alias. The test is still valid in testing `+` and `-` but since the alias `prev` and `next` were discarded, this test should follow suit.

### PR DESCRIPTION
**Pull request by raisfathin**
Fixes #1149

### CODE REVIEW

**Comment by HansNewbie** [comment]
Okay, seems good. Can you merge the latest master branch to this, since this branch now is out-of-date?

**Comment by raisfathin** [comment]
Done. But somehow the travis build failed again.

**Comment by dariusf** [comment]
I've restarted the build. Are you able to restart it yourself via Travis?

By the way, if you see random failures with particular tests, you can help take note of the errors and post them [here](https://github.com/HubTurbo/HubTurbo/issues/952).

**Comment by HansNewbie** [comment]
@dariusf the coverage drop is false. Is the merge, i.e. non-rebased commit, fine with you?

**Comment by dariusf** [comment]
Yeah, it's not a big deal (and also not part of the dev docs officially yet). Just something to encourage because it's useful for contributing to projects that aren't yours -- people have different standards for how clean/linear history should be.

@raisfathin you can try rebasing instead in future when you're comfortable with it.

**Comment by HansNewbie** [comment]
@dariusf Alright. Can you help merge this? Thanks.

**Comment by raisfathin** [comment]
@dariusf Yes, I managed to restart the build yesterday by closing and reopening the issue (is this ok?). Alright, will rebase instead of merge in the future.

@HansNewbie @dariusf Thanks for the help.

**Comment by dariusf** [comment]
Yup. Another way is to push empty commits (then squash them away later). Can you access Travis though?

**Comment by raisfathin** [comment]
@dariusf I see. Yes, I can, why?

**Comment by dariusf** [comment]
If you can see the build for your fork, it can be restarted there without having to do anything here.

**Pull request merged**
