### PR TITLE
Move frequently failing tests to unstable #1369

### LINKED ISSUE #1369: Move frequently failing tests to unstable
There are a couple of tests that passes locally but fails rather frequently on Travis.
This causes delay when trying to merge a PR.

For example:
KeyboardShortcutsTest, particularly in line 146.
ContextMenuTests, methods 'test2' and 'test3'.
IssuePanelsTests, guiElementsTest.

### PR DESCRIPTION
**Pull request by m133225**
Fixes #1369.

### CODE REVIEW

**Comment by m133225** [comment]
@dariusf Should RepositorySelectorTest also be moved to unstable? I think it fails somewhat frequently, and also when this PR is first built :stuck_out_tongue: . (not for me, though.)

**Comment by dariusf** [comment]
Sure, I've seen that fail a few times. If there are any that you see fail randomly, you can take the chance to move them.

**Comment by damithc** [comment]
What's the status of this one? From what I remember, this is blocking many of the ongoing pickers, so let's settle this fast.

**Comment by m133225** [comment]
@dariusf Ready for review.

**Comment by m133225** [comment]
@damithc Should be more or less finalised, unless there are problematic tests to be added that others have encountered.

**Comment by dariusf** [comment]
Yeah, I don't have much more to add.

**Pull request merged**
