### PR TITLE
 Improve testing for mark as read #760 

### LINKED ISSUE #760: Improve testing for mark as read
Add more comments and corner cases.
Assigned to myself.

### PR DESCRIPTION
**Pull request by HyungJon**
Fixes #760 

A few additional test cases and comments.

### CODE REVIEW

**Comment by HyungJon** [comment]
That is unexpected.

**Comment by damithc** [comment]
A PR should not do more than one thing. Create a separate PR for the `.classpath` update as it is unrelated to adding tests.

**Comment by acruis** [comment]
Seems good to go. Any more things to add to this PR?

**Comment by HyungJon** [comment]
Nothing for now.

**Comment by acruis** [comment]
For now? As in later will have?

**Comment by HyungJon** [comment]
Oh sorry, as in nothing as far as I can think of.

**Comment by acruis** [comment]
Alright.

**Pull request merged**
