### PR TITLE
Move installer link to home README page

### LINKED ISSUE #1016: Move installer link to home README page
UX issue - Want to reduce the barriers for the user to install HubTurbo and improve intuitiveness when downloading

### PR DESCRIPTION
**Pull request by codemanmeet**
Fixes #1016.

### CODE REVIEW

**Comment by damithc** [comment]
Before we move the link to the landing page, we should implement a check in HT to verify if the prerequisites are set up is correctly. Otherwise users will simply download the jar file without any idea of the prerequisites.

**Comment by codemanmeet** [comment]
The pre reqs are mentioned in the main page as well. I have included "pre-requisities" and "Installer" as subheadings under "Quick installation" to make sure the users have the necessary pre-requisites. We can add a separate issue to perform a check when the jar file itself is opened.

**Comment by codemanmeet** [comment]
Appears something like this - 
screen shot 2015-10-13 at 6 18 02 pm

**Comment by damithc** [comment]
This has two problems:
1. duplication of information
2. README.md is served from the master branch which may be ahead of the release branch. So the pre-requisites given in README.md may not be compatible with the released version of the app.

**Comment by codemanmeet** [comment]
@damithc @dariusf Do you know how I can serve it from the release branch? 

@damithc Concerning the duplication, shall I remove it from the main User Guide then?

**Comment by damithc** [comment]
May be the easy solution to give a direct link from README to the place where it explains how to install? At this time we don't expect random people to start using HT, so it is not a big problem if the download link is not in the landing page.

**Comment by codemanmeet** [comment]
@damithc Let me know if it looks good now.

**Pull request merged**
