### PR TITLE
Rename File menu item #1356

### LINKED ISSUE #1356: Rename File menu item
The File menu item doesn't contain anything related to files. :stuck_out_tongue: We can probably change the name to 'App'? 'HubTurbo'?

screen shot 2016-03-15 at 1 29 01 am

### PR DESCRIPTION
**Pull request by yl-coder**
Fixes #1356

### CODE REVIEW

**Comment by yl-coder** [comment]
Ready for Review

**Comment by damithc** [comment]
@jinified can review this?

**Comment by yl-coder** [comment]
Not ready for review. I think there's something wrong with the test cases after I renamed it. I will figure it out why.

**Comment by yl-coder** [comment]
@lejolly I have already change all the testcases that require the clicking of "File" to "App". But it is still failing. Do you have any clues on why changing the menuitem "File" to "App" will cause some testcases to fail? It has error like "org.loadui.testfx.exceptions.NoNodesFoundException: No nodes matched '#panel1'. Screenshot saved as /HubTurboForked/screenshot1459395521869.png."

**Comment by damithc** [comment]
@yl-coder which test is failing? Can you get it to pass in your own computer?

**Comment by damithc** [comment]
@xinan how to find the screenshot of the failed test?

**Comment by yl-coder** [comment]
image

**Comment by yl-coder** [comment]
image


I run this on the latest master branch. But there's still error. Did I setup my testing environment correctly?

**Comment by damithc** [comment]
@jinified need help here.

**Comment by xinan** [comment]
@damithc The links are at the end of the Travis build log.

**Comment by yl-coder** [comment]
@jinified Ready for review

**Comment by jinified** [comment]
I think the code is good to go but could you squash some of the noisy commits like those that are not related to the pr like `merge from master`. I think it is better to rebase those changes from master to avoid polluting your pr next time.

**Comment by damithc** [comment]
I wonder what would happen GitHub's new squash feature here. :-p

**Comment by yl-coder** [comment]
@jinified How do i squash merge commits? These commits didn't show up when do git rebase -i now. It only show normal commits like rename file menu to App and Fix failed UI Test cases.

**Comment by jinified** [comment]
@yl-coder can resolve conflict after updating to latest master ?

**Comment by yl-coder** [comment]
@jinified i think there's a lib dependency issue. 

import org.testfx.api.FxRobot;
import org.testfx.api.FxToolkit;

gradle manage to download them and run successfully, but the main source code doesn't have the lib file i think.

**Comment by jinified** [comment]
Are you saying the code can't compile locally ? Did you try refreshing your Gradle model ?

**Comment by yl-coder** [comment]
yes. But its alright now. After I set auto-import in my gradle setting. thanks

**Comment by damithc** [comment]
@jinified please merge.

**Comment by jinified** [comment]
@yl-coder Could you resolve the conflict ? I will help you merge after you are done

**Comment by yl-coder** [comment]
@jinified conflict resolved

**Pull request merged**
