### PR TITLE
milestone picker: up/down keys don't work #1517

### LINKED ISSUE #1517: milestone picker: up/down keys don't work
Up/down keys do not navigate the top 5 matches as they are expected to

### PR DESCRIPTION
**Pull request by m133225**
Fixes #1517.

### CODE REVIEW

**Comment by m133225** [comment]
Ready for review. Fix of a simple mistake that should have been avoided in #1507.

**Comment by damithc** [comment]
Any chance this could have been avoided (or at least prevent regressions) with a test?

**Comment by ndt93** [comment]
@m133225 Can you update to the current master and try to pass the CI? Thanks.

**Comment by m133225** [comment]
@ndt93 Done.

**Pull request merged**
