### PR TITLE
Added guide to run a single test using gradlew #1189

### LINKED ISSUE #1189: Add guide to run a single test using gradlew

### PR DESCRIPTION
**Pull request by jinified**
Fixes #1189

### CODE REVIEW

**Comment by dariusf** [comment]
Thanks! Couple of minor things:

- PRs are supposed to fix issues, so there needs to be an accompanying issue for this. I know it's a bit trivial in this case, but could you create that issue and link it to this PR? Fixes #x, title, etc. Just so you're familiar with the whole process.
- If you're comfortable with rebasing, it'd be good to do that for updating to the latest master, especially if it's not a difficult merge and doesn't need to be preserved. Helps keep history a bit cleaner.

**Comment by jinified** [comment]
Fixes #1189

**Comment by dariusf** [comment]
The 'fixes' string has to be in the description of the PR for the issue to close automatically. You have to edit and insert it in there.

The title should also have the issue number at the back.

**Comment by dariusf** [comment]
Thanks!

**Pull request merged**
