### PR TITLE
User can name a panel #782

### LINKED ISSUE #782: User can name a panel
so that user can give a descriptive name to a panel e.g. `recent high priority updates` `PRs I'm reviewing` etc.

### PR DESCRIPTION
**Pull request by HyungJon**
Fixes #782 

Note: running HubTurbo with this PR merged will delete all saved filters because the save function works differently now.

There are currently clashes with the way boards are saved, resulting in panel names being reset when opening a new board. I will fix it in a fresh issue.

### CODE REVIEW

**Comment by HyungJon** [comment]
This is strange. I started getting ```chromeDriverTest``` failure even at master branch but never on Travis build so I assumed the failure is caused by some anomaly on my local machine only, but it is failing Travis build now.

And I never got the ```basicPanelInfoTest ``` failure on my local machine and the cause for build failure is not being able to find the node ```dummy/dummy_col1_``` + filter box or rename button, something that should not be failing. I have no idea why I get this second failure. I will look into it tomorrow.

**Comment by damithc** [comment]
I too get ChromeDriver test failures from time to time. Seems it doesn't
happen if you do a 'clean test'

**Comment by HyungJon** [comment]
I found a likely cause for ChromeDriverTest failure in #802. I'm very confused about the Panel info test, especially why Travis is trying to find a node called "Node should have label Quit" now.

**Comment by lejolly** [comment]
@HyungJon the test is asking TestFX to click on a `Node` with the label `Quit` right in `PanelInfoBasicTest:54`?

**Comment by HyungJon** [comment]
Yes, to quit the program. For some reason it fails to find the Quit button. And I noticed it also failed to find columns sometimes, both of which didn't happen on my machine.

**Comment by lejolly** [comment]
You could try to use the arrow keys to select the `Quit` menu item. The ci doesn't run exactly like a local machine, so expect some quirks.

**Comment by HyungJon** [comment]
All failures resolved except an error that makes CI unable to read the data stored in the config file properly. I really have no idea what could be causing this, ```UseGlobalConfigsTest``` passes with no problem.

**Comment by lejolly** [comment]
try adding a delay, HT doesn't save and quit instantly, especially on the ci.

**Comment by HyungJon** [comment]
It appears nothing gets saved to the config file, based on the assertionError when I tested the last open repo value. I increased ```EVENT_DELAY``` to 4000 which did not solve the issue. 

p.s.) Is there a way to run a CI build without pushing?

**Comment by lejolly** [comment]
i think you can try to close and open the pr?

**Comment by lejolly** [comment]
firstly i can't get `PanelInfoBasicTest` to pass locally. 

```
org.junit.ComparisonFailure: 
Expected :new panel
Actual   :Dummy 2 repo
 <Click to see difference>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at guitests.PanelInfoBasicTest.basicPanelInfoTest(PanelInfoBasicTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

secondly, be careful when testing for dialogs, the ci has a habit of not being able to type in dialog text fields. take a look at `LabelPickerTests` for some ideas (namely the ci can't seem to handle more than one window/dialog at a time well).

**Comment by dariusf** [comment]
You can restart a Travis build from their site (button on the right). Setting up a CI environment locally is [possible](https://github.com/travis-ci/travis-ci/issues/2114) but looks involved.

Anyway, it would be great if you could squash the noisy commits (attempted fixes, merges, linting errors, etc.) before this is merged.

**Comment by HyungJon** [comment]
Uk, I seem to have done something wrong when trying to squash. I'll do it after the issue is solved. Pushing again.

**Pull request closed without merging**
