### PR TITLE
Add divider between label groups #786

### LINKED ISSUE #786: Add  divider between label groups
... to make it look more organized. A blank line or a subtle divider line?
image

### PR DESCRIPTION
**Pull request by lejolly**
Fixes #786

edit_labels_for_pr__823_in_hubturbo_hubturbo

### CODE REVIEW

**Comment by damithc** [comment]
Make the group name bold? Or do some other thing to make it stand out a bit more.
Indent the labels of a group a bit? Currently group name and labels are indented at the same level.
How to show labels without a group?

**Comment by damithc** [comment]
May be show the dot/dash as well, because that indicates nature of the group?

**Comment by lejolly** [comment]
something like that?

edit_labels_for_issue__10_in_dummy_dummy

**Comment by damithc** [comment]
Yes, but I prefer 'p.' rather than 'p (exclusive)'. Shorter and the meaning
of the dot is something the user knows already.

**Comment by damithc** [comment]
Put ungrouped ones at the bottom rather than on the top? I feel the
ungrouped ones are the less important and less used ones.

**Comment by damithc** [comment]
And a tiny bit more space between groups?

**Comment by lejolly** [comment]
do we still need to indent the group labels?

edit_labels_for_issue__10_in_dummy_dummy

**Comment by damithc** [comment]
Looks good. Yes, let's keep the indentation.

**Comment by lejolly** [comment]
ok

**Comment by damithc** [comment]
For toggle.png, can use a more representative string e.g. `hi d.b u`
It is unlikely that we can use just a sequence of single letters to select the labels we actually want.

**Comment by acruis** [comment]
Great refactoring! The label picker is a lot clearer now. Good to merge.

**Pull request merged**
