### PR TITLE
keyword search broken for large repos? #838

### LINKED ISSUE #838: keyword search broken for large repos?
When trying with homebrew, keyword search does not seem to narrow down search results. e.g. `is:open` and `is:open fix` seem to give the same result set.

### PR DESCRIPTION
**Pull request by acruis**
Fixes #838

### CODE REVIEW

**Comment by dariusf** [comment]
Maybe it would be better to fix this at the model level? By the time we get to the level of TurboIssue objects, the null fields should have default values.

**Comment by damithc** [comment]
Yup, a lower level fix is better. Rest of the code should be able to operate as if this inconsistency does not exist.

**Comment by acruis** [comment]
Alright, got it.

**Comment by dariusf** [comment]
Looks good. Would be great if you could squash this (the original commit is no longer relevant).

**Pull request merged**
