### PR TITLE
Run unstable tests separately #1024

### LINKED ISSUE #1024: Run unstable tests separately
Devs/reviewers will manually check these. The Travis build should be as deterministic as possible. Related to #952.

### PR DESCRIPTION
**Pull request by dariusf**
Fixes #1024.

Docs will be updated separately in #947 and #757.

### CODE REVIEW

**Comment by dariusf** [comment]
An environment variable is used to control whether the unstable tests run. This is the simplest solution I could get to work. Tried splitting the tests up into source sets, but that caused problems with coverage (the task doesn't support computing coverage from multiple source sets by default). I'm still not sure how to define a task that operates on a subset of a default task's inputs.

@lejolly do you know if jacocoTestReport is needed? AFAIK it's not used. The parameter it supplies to jacocoRootReport has the default value.

**Comment by dariusf** [comment]
Forgot to rename the task. I'm thinking of calling it either `testUnstable` or `unstableTests`. The first follows conventions, the second is more descriptive. Opinions welcome.

**Comment by lejolly** [comment]
not sure if `jacocoTestReport` was needed, possibly to generate both html and xml reports locally?

i would go with `unstableTests`.

**Comment by dariusf** [comment]
Renamed. In that case, I think it isn't needed. jacocoRootReport does the same thing.

Added a couple more unstable tests.

**Comment by dariusf** [comment]
Added MenuControlTest. I think that should be all for now, unless there are other suggestions. We don't have too many samples, so I've only added those I've seen fail 2-3 times in the recent PRs.

**Comment by lejolly** [comment]
Got this on the second restart of the build. 

```
guitests.MetadataUpdateTest > testUpdatedTriggersMetadata FAILED
    java.lang.RuntimeException: java.lang.NullPointerException
        at org.loadui.testfx.utils.TestUtils.awaitCondition(TestUtils.java:49)
        at org.loadui.testfx.utils.TestUtils.awaitCondition(TestUtils.java:30)
        at guitests.MetadataUpdateTest.testUpdatedTriggersMetadata(MetadataUpdateTest.java:24)
        Caused by:
        java.lang.NullPointerException
            at org.loadui.testfx.utils.FXTestUtils.isNodeWithinSceneBounds(FXTestUtils.java:249)
            at org.loadui.testfx.utils.FXTestUtils.isNodeVisible(FXTestUtils.java:242)
            at org.loadui.testfx.utils.FXTestUtils$6.apply(FXTestUtils.java:233)
            at org.loadui.testfx.utils.FXTestUtils$6.apply(FXTestUtils.java:230)
            at com.google.common.collect.Iterators$7.computeNext(Iterators.java:652)
            at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
            at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
            at com.google.common.collect.Iterators.getNext(Iterators.java:865)
            at com.google.common.collect.Iterables.getFirst(Iterables.java:775)
            at org.loadui.testfx.GuiTest.find(GuiTest.java:466)
            at org.loadui.testfx.GuiTest.find(GuiTest.java:306)
            at guitests.UITest.findQuiet(UITest.java:211)
            at guitests.MetadataUpdateTest.lambda$testUpdatedTriggersMetadata$20(MetadataUpdateTest.java:25)
            at org.loadui.testfx.utils.TestUtils.awaitCondition(TestUtils.java:38)
            ... 2 more
```

**Comment by dariusf** [comment]
Added that. It's already in the nondeterministic test issue.

**Comment by lejolly** [comment]
i think you forgot to update the findbugs exception file?

```
Write to static field ui.UI.status from instance method unstable.SavedLoginTest.setupMethod()
```

**Comment by dariusf** [comment]
Yeah, just realised.

**Comment by dariusf** [comment]
Passed another 5 times. Another failure from RepositorySelectorTest so I removed it as well.

So when do we decide if the CI build is stable enough?

**Comment by lejolly** [comment]
i guess 100% passing rate is kinda unattainable? 90%? 80%?

**Comment by dariusf** [comment]
Passed 9 more times. Not the most formal experiment, but we're at 20/22 (90.9%) now.

**Comment by lejolly** [comment]
Ok, good to merge then. We can always include more tests in the future if they're giving us problems.

**Pull request merged**
