### PR TITLE
Add a way to filter out self updates from the 'updated' filter

### LINKED ISSUE #898: Add a way to filter out self updates from the 'updated' filter
e.g. some special character to indicate that self updates should be ignored

### PR DESCRIPTION
**Pull request by codemanmeet**
Fixes #898

### CODE REVIEW

**Comment by damithc** [comment]
PR title should match the issue title.

**Comment by damithc** [comment]
Our usual practice is to assign milestones to issues, not PRs.

**Comment by damithc** [comment]
I don't think the PR name is still correct. Don't take a best guess. Follow precisely instead. You can also look at other PRs to see examples.

**Comment by damithc** [comment]
One more thing: the branch name doesn't follow the convention.

**Comment by codemanmeet** [comment]
Prof., I renamed the branch but somehow the pull request got closed. I have created a new pull request with the renamed branch.

**Pull request closed without merging**
