### PR TITLE
Correct the swapped parameters for assertEquals #1281

### LINKED ISSUE #1281: Correct the swapped parameters for assertEquals
Many `assertEquals(expected, actual)` have its parameters swapped.

ex. At BoardAutoCreatorTest.java,

> assertEquals(panelControl.getPanelCount(), 5);
> assertEquals(panelControl.getCurrentlySelectedPanel(), Optional.of(0));
> assertEquals(panelControl.getNumberOfSavedBoards(), 1);

should instead be

> assertEquals(5, panelControl.getPanelCount());
> assertEquals(Optional.of(0), panelControl.getCurrentlySelectedPanel());
> assertEquals(1, panelControl.getNumberOfSavedBoards());

### PR DESCRIPTION
**Pull request by garbanzos**
Fixes #1281. 

Checked the tests in packages:  
- [x] guitests 
- [x] tests
- [x] unstable

### CODE REVIEW

**Comment by garbanzos** [comment]
I noticed that there are unused imports in tests: 
- guitests/BoardTests
- guitests/InvalidLoginTest
- guitests/PanelsTest 
- guitests/StartupBoardLauncherTest
- tests/EventTests
- tests/RepositorySelectorPopulationTest
- tests/ScreenManagerTests 
Should I remove them?

**Comment by damithc** [comment]
I guess it's ok to remove unused imports in this PR.

**Comment by garbanzos** [comment]
Removed the unused imports and corrected the swapped parameters for assertEquals.

**Comment by garbanzos** [comment]
Ready for review.

**Comment by garbanzos** [comment]
@dariusf could you help to review?

**Comment by dariusf** [comment]
Looks good.

**Pull request merged**
