### PR TITLE
Show closed issues in a different fill color

### LINKED ISSUE #1068: Show closed issues in a different fill color
e.g. change the fill color of closed issues into a light shade of green. That way, a panel sorted by status will look like a container filling up (like a vertical progress bar). This will make the 'milestones' board look nice.

### PR DESCRIPTION
**Pull request by codemanmeet**
Fixes #1068.

### CODE REVIEW

**Comment by codemanmeet** [comment]
@damithc Would appear something like this - 
closed_issue

**Comment by damithc** [comment]
I prefer a more subtle shade. Is it still possible to maintain the zebra style?

**Comment by codemanmeet** [comment]
The shade of green is more subtle now. This is how it looks - 
closed_issue2

**Comment by dariusf** [comment]
The blue on green is a bit... loud. Also are we doing zebra stripes?

**Comment by damithc** [comment]
I'm hoping for lighter, almost same level as the darker gray of the current two colors. Also, look for a less flashy green. The current one is luminous green. 
As darius mentioned, I can't see the zebra pattern.

**Comment by codemanmeet** [comment]
I want to maintain the selected issue color to be blue as it is consistent for other issues too. The zebra stripes are inherent to JavaFX [list-cells](http://stackoverflow.com/questions/18694447/how-can-we-set-a-particular-color-for-selected-item-on-listview-in-java-fx). The zebra stripes make sense when they are applicable for all cells and if all cells are in order. Here, the closed issues might be mixed with open issues so it would look odd to have them zebra that way.

**Comment by damithc** [comment]
Something like this? 
image

**Comment by codemanmeet** [comment]
Sure, I got the zebra to work too!

**Comment by codemanmeet** [comment]
I used d8e8d3 and darkened it by 3% for odd cells.
It looks like this now - 

closed_issue3

**Comment by codemanmeet** [comment]
Let me know if the above looks fine!

**Comment by damithc** [comment]
Make a bit more lighter? Post screenshot with both open and closed ones.

**Comment by codemanmeet** [comment]
Alright made it even lighter! Looks like this now - 
closed_4

**Comment by damithc** [comment]
I'm ok with the color. Go ahead.

**Comment by codemanmeet** [comment]
@dariusf Let me know if it is ok to merge :)

**Comment by dariusf** [comment]
Code is fine. Could you squash? No need to wait for CI.

**Pull request merged**
