### PR TITLE
json explosion false positive for large repos #821

### PR DESCRIPTION
**Pull request by acruis**
Does not fully finish #821.

### CODE REVIEW

**Comment by lejolly** [comment]
waiting for the download count limit to be added

**Comment by acruis** [comment]
Fixes #821

**Comment by damithc** [comment]
@lejolly can review this quickly?

**Comment by lejolly** [comment]
Do we want to show an error message when we reach the download limit without being able to successfully download the repo?

**Comment by damithc** [comment]
Yes, that would be better. Just a simple, 'could not download, it is unexpected, please let us know if you encounter this' kind of message.

**Comment by lejolly** [comment]
ok, looks good.

**Pull request merged**
