### PR TITLE
Board picker: Cannot pick board by clicking #1499

### LINKED ISSUE #1499: Board picker: Cannot pick board by clicking
In this case I have no way to pick the board 'updates' either by clicking or typing!
image

### PR DESCRIPTION
**Pull request by xinan**
Fixes #1499

### CODE REVIEW

**Comment by damithc** [comment]
Ahem, wrong PR title :-|

**Comment by xinan** [comment]
😅 You meant missing issue number?

**Comment by damithc** [comment]
The PR name should be same as issue name. You didn't know? :open_mouth:

**Comment by xinan** [comment]
I know. But I always tend to add a "Fix" in front. Isn't that more intuitive? 😳

**Comment by damithc** [comment]
Our convention is to use the same title. Easier to locate the corresponding issue/PR that way.

**Comment by ndt93** [comment]
@xinan Can rename the PR's title :-) ? As of now, the convention is as damith mentioned. Having less ambiguities in a convention can help us with managing across multiple issues and pull requests.

**Comment by xinan** [comment]
Done! 😄

**Pull request merged**
