### PR TITLE
Milestone picker: use lighter colors for open/close #1409

### LINKED ISSUE #1409: Milestone picker: use lighter colors for open/close
We can use lighter red/green to make them easier to read

### PR DESCRIPTION
**Pull request by garbanzos**
Fixes #1409. 

image

### CODE REVIEW

**Comment by garbanzos** [comment]
@damithc Are these colours ok?

**Comment by damithc** [comment]
They are ok. A tiny bit lighter is even better.

**Comment by garbanzos** [comment]
@damithc It this better?
image

**Comment by damithc** [comment]
Yes, colors look good.

**Comment by garbanzos** [comment]
@damithc Is this merge approved?

**Comment by damithc** [comment]
@m133225 can you review this?

**Comment by m133225** [comment]
@damithc Actually, would making the font white(which is what label picker does when the background is too dark) be better than making the colours lighter ? Since the only purpose for the change is to make it easier to read. The colour will then be consistent with GitHub's ones too.

**Comment by damithc** [comment]
I prefer lighter colors because brighter colors attract attention unnecessarily. In this UI, the open/closed/overdue status is not the most important information and hence should not be shown in the brightest colors.

**Comment by m133225** [comment]
If that's the case, then I have no further comments for this PR since it is rather straightforward. :stuck_out_tongue:

**Pull request merged**
