### PR TITLE
Fix tick not appearing properly in LabelPicker #1332

### LINKED ISSUE #1332: Label picker: tick mark is shown as '...'
Happens in my laptop but not my office comp
image

### PR DESCRIPTION
**Pull request by jinified**
Fixes #1332

### CODE REVIEW

**Comment by ndt93** [comment]
Is this PR ready for review?

**Comment by jinified** [comment]
Yup. But need to verify if the changes work @damithc. I don't seemed to have the problem on my computer

**Comment by damithc** [comment]
Check if any of your team members have the same issue and can be the guinea pig :-p

**Comment by ndt93** [comment]
@jinified Can update to the current master? And have you been able to verify this with someone who has this problem.

**Comment by jinified** [comment]
still getting people to test the problem

**Comment by damithc** [comment]
It's working for me.

**Comment by damithc** [comment]
Ahem, this PR title doesn't appear to match the issue @jinified

**Pull request merged**
