### PR TITLE
Implement toString() for classes in backend.resource.serialization #794

### LINKED ISSUE #794: Implement toString() for classes in backend.resource and backend.resource.serialization
So that it's more convenient for logging and debugging

### PR DESCRIPTION
**Pull request by ndt93**
Resolves #794

### CODE REVIEW

**Comment by ndt93** [comment]
UserGlobalConfigsTest doesn't seem to be very stable so I increased the timeout to pass the CI here. But it would be nice if anyone who is familiar with the code can look into it for a proper fix.

**Comment by acruis** [comment]
This is a known problem, actually just restarting the CI build will get the tests to pass most of the time (i.e. UseGlobalConfigsTest just has a chance to fail). For now, comment when you're done with the PR and we'll reset the builds on the CI.

**Comment by ndt93** [comment]
Ok sure. I closed and opened the pull request again to trigger a rebuild for this actually. I should be done with the PR.

**Comment by acruis** [comment]
Alright, good to merge.

**Pull request merged**
