### PR TITLE
Label Picker #740

### PR DESCRIPTION
**Pull request by lejolly**
Implements #740

### CODE REVIEW

**Comment by lejolly** [comment]
some progress

edit_labels_for_issue__744_in_hubturbo_hubturbo

**Comment by acruis** [comment]
Added backend support for replacing issue labels. When the GUI is ready, switch the current `replaceIssueLabels` method in RepoIO with the currently-commented out one below it.

**Comment by lejolly** [comment]
final UI for label picker

edit_labels_for_issue__765_in_hubturbo_hubturbo

**Comment by damithc** [comment]
Don't spend a lot of time polishing/testing this UI because it is not what
I want. But ok as a first version. In the UI I have in mind, label
selection will be done by typing part of the label rather than
navigate/toggle approach.

**Comment by lejolly** [comment]
like this?

hubturbo

**Comment by damithc** [comment]
Label dialog goes out of screen for some issue.
image

**Comment by lejolly** [comment]
would you prefer it to appear in the middle of the screen?

**Comment by damithc** [comment]
Enter key should apply the last label in-progress. e.g. `bu`<kbd>enter</kbd> should be as same as `bu`<kbd>space</kbd><kbd>enter</kbd>

**Comment by lejolly** [comment]
ok

**Comment by damithc** [comment]
I think the position depends on where the issue card is. Ideally, the dialog should appear as close to the issue card as possible, should not cover the issue card, and should not go out of the screen.

**Comment by lejolly** [comment]
ok, i might tackle that after changing the `TextField` behaviour. But i can't reproduce the going out of the screen issue on OS X.

**Comment by damithc** [comment]
I'm ok with the current UI. Add tests, update user docs, get it reviewed and merge :-)

**Comment by lejolly** [comment]
ok will make some minor changes and then work on getting it ready to merge

**Comment by lejolly** [comment]
@damithc 2 changes
1. labels in the picker will now show the full label names including the groups to reduce confusion for situations such as: `p.low` and `d.low`
2. searching by groups is now supported using `p.` should display `priority.low`, `priority.medium` and `priority.high`, thus typing `p.l` should select `p.low` or `priority.low`

**Comment by damithc** [comment]
Nice work. May be sort by group? i.e.
aspect labels
[blank line] 
priority labels
[blank line]
...
[blank line]
regrouped labels

It not trivial to do, can do later as a separate issue.

**Comment by lejolly** [comment]
@damithc could you see if the latest commit fixes #789?

**Comment by damithc** [comment]
Yes, it is better now. Adding the tick now moved the next label a few pixels, not as much as before. The other time the whole label list shifts is when the list of labels (above the text box) spills over to the next line.

**Comment by acruis** [comment]
Good to merge!

**Pull request merged**
