### PR TITLE
Cache dependencies on Travis

### LINKED ISSUE #1370: Cache dependencies on Travis to make building faster
Every build on Travis is downloading all the dependencies, which takes quite an amount of time. 
We should try caching the dependencies to reduce the waiting time. 

The Travis Doc mentioned a way to do this:
https://docs.travis-ci.com/user/languages/java#Caching

### PR DESCRIPTION
**Pull request by xinan**
Closes #1370

### CODE REVIEW

**Comment by ndt93** [comment]
@xinan Is this ready for review?

**Comment by ndt93** [comment]
Since ours is not a private repository, we need to use Travis' [container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) to enable caching support.

**Comment by xinan** [comment]
@ndt93 It is ready for review! I added all these trivial commits just to test the caching, but unfortunately the master build is failing intermittently. :sweat_smile: I think we are already using container-based infrastructure?

**Comment by ndt93** [comment]
We need to add `sudo: false` to .travis.yml to use the container-based infrastructure?

**Comment by ndt93** [comment]
Also rebase to the current master, shouldn't have any conflicts with this PR I suppose.

**Comment by xinan** [comment]
Actually no need. If you look at the log (line 236), it says
> This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
> If you require sudo, add 'sudo: required' to your .travis.yml
> See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

And caching works too! (From line 246)
> Setting up build cache
> $ export CASHER_DIR=$HOME/.casher
> $ Installing caching utilities
> 
> attempting to download cache archive
> fetching PR.1371/cache--jdk-oraclejdk8.tgz
> found cache
> 
> adding /home/travis/.gradle/caches to cache
> adding /home/travis/.gradle/wrapper to cache

**Comment by ndt93** [comment]
Ah ok, that's great then.

**Pull request merged**
