### PR TITLE
Fix NPE in findQuiet #1335

### LINKED ISSUE #1335: Fix NPE in findQuiet
As discussed [here](https://github.com/HubTurbo/HubTurbo/issues/1263#issuecomment-190749350). The fix is to use `ofNullable` instead.

### PR DESCRIPTION
**Pull request by leonardhml**
Fixes #1335

### CODE REVIEW

**Comment by leonardhml** [comment]
This is ready for review.

**Comment by dariusf** [comment]
Thanks for the fix! Do check out the [development process](https://github.com/HubTurbo/HubTurbo/blob/master/docs/process.md) for how to title your PR.

Also, there's no need to mention the line number in the commit message, as that metadata is available in the commit already. Could you amend that as well?

**Comment by leonardhml** [comment]
Done! Apologies for the error in the title and commit message.

**Comment by dariusf** [comment]
Thanks!

**Pull request merged**
