### PR TITLE
Give a keyboard shortcut to jump from the filter box to the first issue in the panel #315

### LINKED ISSUE #315: Give a keyboard shortcut to jump from the filter box to the first issue in the panel
Most of the time we are on the keyboard when typing a filter. It's nice if we can remain in the keyboard when moving to the issue list from there.

### PR DESCRIPTION
**Pull request by rd1992**
Hardcoded to CTRL + R in IssuePanel.java
Fixes #315

### CODE REVIEW

**Comment by damithc** [comment]
Why R?
perhaps Ctrl+ down arrow is more intuitive?

**Comment by damithc** [comment]
Actually, Ctrl+down arrow makes sense only if the focus is on the filter box. If we want a general shortcut to go to the first issue, we might have to choose another shortcut. Ctrl+up to go to first and Ctrl+down to go to last?

**Comment by damithc** [comment]
@dariusf why this is not reviewed yet?

**Comment by rd1992** [comment]
@damithc i am making changes on it. need to do select last issue. only first issue selection is done.

**Comment by dariusf** [comment]
I thought it was still ongoing. It's still Ctrl+R now. Are we changing this?

Also, do we need a hotkey for going to the last issue? Home and End should work after we jump to the issue list from the filter box.

**Comment by rd1992** [comment]
@dariusf yeah am changing it. Keeping it to Shift + down arrow from filter box.

**Comment by damithc** [comment]
In that case, no need for a hot key to jump to the last one.
I noticed that home and end keys make the selection jump to top and bottom, but the issues don't load in bView.

**Comment by damithc** [comment]
Shift is used to navigate without loading issues. So I'm not sure if Shift
is suitable for jumping to first issue if the jump results in loading the
issue.

**Comment by damithc** [comment]
Perhaps Ctrl+down to jump and load, Shift+down just to jump without loading?

**Comment by rd1992** [comment]
Then shift + down seems redundant. If the user wants to view the first issue, he will have to do either control + down (which is straightforward) or shift + down followed by down arrow and then up arrow. Until and unless we keep ENTER as the way of loading the issue in bView? then even after a user presses shift + down or home or end key followed by ENTER the issue loads in bView.

**Comment by damithc** [comment]
Shift+down is unlikely to be used a lot, except when the user wants to load
an issue other than the first one. e.g. type the filter, press enter,
notices the third issue as the one he wants to view, press shift+down three
times to get there, and press enter to load.

**Comment by rd1992** [comment]
Well i have set it to control + down for now. Shift + Down functionality is not clear to me so havent implemented it.

**Comment by rd1992** [comment]
@dariusf can you merge this?

**Pull request merged**
