### PR TITLE
Some repos not saved as json files #1065

### LINKED ISSUE #1065: Some repos not saved as json files
I have powerpointlabs/powerpointlabs as a repo in my filters. Turns out it is never saved to the hard disk. Everytime I start HT, the repo is downloaded again.

### PR DESCRIPTION
**Pull request by HansNewbie**
Fixes #1065

### CODE REVIEW

**Comment by damithc** [comment]
I'm also interested to know how this bug got through and how to prevent something like that happening again.

**Comment by HansNewbie** [comment]
The bug was caused by using a local variable instead of the supposed class variable. If you would like to prevent it to be happening again, the solutions I can think of are for `checkStyle` to check either:
- no local variable has same name as class variable except in constructor.
- all class variable should use `this.` reference so the next developer know that they should use class variable.

I am not sure if they are possible to be included in `checkStyle`, though.

**Comment by ndt93** [comment]
This bug and similar major bugs happening recently are from the download and update process i.e. interactions with GitHub which we technically don't have any test for. These bugs only crop up in scenarios which we could miss, e.g. for this one I only check for the updating part but never try downloading a new repo. So ideally we could have some kinds of mock-ups to test these parts.

Beside, how does the json files get deleted in the first place?

**Comment by HansNewbie** [comment]
Using remove repo option. That removes the JSON file.

**Comment by ndt93** [comment]
Ok, I see. This fix can be merged then.

**Comment by HansNewbie** [comment]
Ok.

**Pull request merged**
