### PR TITLE
 Ctrl+R is triggering a 'reply' action #907 

### LINKED ISSUE #907: Ctrl+R is triggering a 'reply' action
When I use the Ctrl+R shortcut, it changes the repo, but also trigger a 'reply' action.

### PR DESCRIPTION
**Pull request by HyungJon**
Fixes #907

### CODE REVIEW

**Comment by dariusf** [comment]
I think a better solution here would be to change all `KeyCode`s into `KeyCodeCombination`s, and use `match` instead of `==` to check equality everywhere.

```java
public static final KeyCodeCombination NEW_COMMENT = new KeyCodeCombination(KeyCode.R);

if (KeyboardShortcuts.NEW_COMMENT.match(event) && ...) {
    // ...
}
```

Using ad-hoc conditional checks will get messy when we start using more chords -- <kbd>Shift</kbd>+<kbd>R</kbd> will require another exception, so will <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>R</kbd>, etc.

Also, we can static import the `KeyboardShortcuts` enums and `KeyCode` constants in files where we use them a lot.

**Comment by HyungJon** [comment]
Done except importing the enums part.

**Comment by dariusf** [comment]
Why not, explicitness? It seems awfully verbose.

I think the `KeyPress` interface should be changed as well, but we'll do that in the other issue.

**Comment by HyungJon** [comment]
Just a status report, I'm working on it. I'm very pressed with overlapping assignments right now though. Can it be done in an another issue, maybe along with that ```KeyPress``` interface changing?

**Comment by dariusf** [comment]
No worries. In that case there's nothing more to do here.

**Pull request merged**
