### PR TITLE
Fix Milestone Picker not handling GitHub failure response properly #1443

### LINKED ISSUE #1443: Milestone Picker: Not handling GitHub failure response properly.
Besides that, it has a similar problem as #1433

### PR DESCRIPTION
**Pull request by xinan**

### CODE REVIEW

**Comment by damithc** [comment]
Name the PR to match the issue.

**Comment by ndt93** [comment]
The fix seems good to me. Although, these should have been caught with just back-end unit tests.

@xinan Do you think it's better to add tests here to safeguard this scenario or wrap up this fix first?

**Comment by ndt93** [comment]
@xinan Let me know if you are not intending to write more tests for this. I think we can merge it as it is. Also there are conflicts with the current master.

**Comment by xinan** [comment]
@ndt93 Sorry I was a bit busy last weekend and I overlooked this PR. There are tests in `LogicTests` though. They seem have covered this part of the code but strangely they did not catch the bug. I am still looking into it.

**Comment by ndt93** [comment]
All rights. No problem :-)

**Comment by xinan** [comment]
@ndt93 I think we shall get this merged first and I will create another issue for the tests.

**Comment by ndt93** [comment]
@xinan This branch has conflicts with master. Can you try resolve that?

**Comment by xinan** [comment]
:open_mouth: It says no conflicts to me. Anyway I will just update the branch.

**Comment by ndt93** [comment]
Oh as in the CI is failing, can you try to pass it?

**Comment by xinan** [comment]
I have been restarting it. But each time it fail a different one 😞 probably due to #1474

**Pull request merged**
