### PR TITLE
pView does not auto-scroll to the selected card when the selection goes out of the visible area #774

### LINKED ISSUE #774: pView does not auto-scroll to the selected card when the selection goes out of the visible area
as per title. Let me know if not clear.

### PR DESCRIPTION
**Pull request by lejolly**
Fixes #774

### CODE REVIEW

**Comment by lejolly** [comment]
it now calls scroll to item when the selection has been restored, the problem is that the scrolling only partially works.

**Comment by lejolly** [comment]
scrolling issues can be solved by eliminating scrolling animations (which is a custom implementation by HT)

current implementation
flow1

native implementation of scrolling without any animations
flow2

@damithc what do you think?

**Comment by lejolly** [comment]
the previous commit changes the scrolling to the native implementation, @damithc could you try it out and see if it works for you?

**Comment by lejolly** [comment]
can be dogfood-ed to see if the new behaviour is acceptable.

**Comment by damithc** [comment]
The current version 'scrolls selection to top' (the selected issue goes to
the top of the panel) which is not suitable. When the selection is visible,
no scrolling should happen. If the selection goes out of the visible area,
the list should auto-scroll just enough to bring the selected issue into
view. That is the 'normal' auto-scroll behaviour expected of a list panel.

**Comment by damithc** [comment]
I was watching the GUI tests and noted that auto-scrolling seems to work fine in those tests where there is a long list of issues.

**Comment by lejolly** [comment]
but in actual use i think the rate of success is a lot lower.

**Comment by damithc** [comment]
It may be because I had a second monitor on the left (it went out of the
first monitor but still showed up in the 2nd monitor)

**Comment by lejolly** [comment]
@damithc does the latest version still scroll if the selection is visible?

**Comment by damithc** [comment]
Which branch should I try?

**Comment by lejolly** [comment]
The Issue774 branch

**Comment by damithc** [comment]
Better, but not there yet. Current situation: Let's say 10 cards are
visible. If I navigate from 10th to 11th, the 11th scrolls to the top and
panel shows cards 11-20. Desired: scroll by one card so that cards 2-11 are
visible.

**Comment by damithc** [comment]
Actually, scrolling of the label picker branch is better. the only problem
is the success rate is not 100%. Sometimes scrolling is as expected,
sometimes not enough (the selected card does not become visible completely).

**Comment by lejolly** [comment]
Yes the original version of scrolling works exactly the way you want it, the only problem is that it isn't entirely reliable, so it's really up to you which version you prefer. I haven't found a foolproof fix for the current version.

**Comment by damithc** [comment]
Is it possible to tweak the original version to auto-scroll to the card
that is just below the selected card, instead of trying to scroll to the
selected card?

**Comment by lejolly** [comment]
That's possible but I don't think it'll solve the problem, will try it out tomorrow.

**Comment by damithc** [comment]
The current one (i'm on label picker branch) seems to work most of the time. We can also use Ctrl+down to scroll at times it doesn't work. while it is not ideal, it is not totally unusable either. See if you can improve the success rate a bit. If cannot, we can KIV this as it is not that important.

**Comment by dariusf** [comment]
Some context on this problem in #290. `ScrollableListView` was actually supposed to address the shortcomings of the native `scrollTo`, and this issue of only being able to show a card by moving it to the top. It does need more polish though.

Would it be possible to compute Y_OFFSET dynamically (based on card height), instead of using a constant? That would solve the problem of cards not becoming completely visible.

**Comment by damithc** [comment]
What happened to this PR?

**Comment by lejolly** [comment]
um, it hasn't been fixed yet, but i'm closing this pr for now because all the stuff i did in the past is now invalid on the latest master. 

also, since this doesn't happen all the time and repeatedly pressing the same key eventually gives the desired result (for scroll to top/bottom), i guess this isn't such a high priority now.

**Pull request closed without merging**
