### PR TITLE
CONTRIBUTING.md should also reference process.md #1338

### LINKED ISSUE #1338: CONTRIBUTING.md should also reference process.md
Currently only points to [dev guide](https://github.com/HubTurbo/HubTurbo/blob/master/docs/developerGuide.md) and [workflow.md](https://github.com/HubTurbo/HubTurbo/blob/master/docs/workflow.md). Making [**process.md**](https://github.com/HubTurbo/HubTurbo/blob/master/docs/process.md) immediately visible from [CONTRIBUTING.md](https://github.com/HubTurbo/HubTurbo/blob/master/CONTRIBUTING.md) means that new contributors will be handed the following information on a silver platter:

1. The guidelines and conventions for submitting pull requests
2. Exposes how pull requests are approved for merging. 

This change should (hopefully) let new contributors catch simple problems in their PRs without a dev having to step in.

### PR DESCRIPTION
**Pull request by SherryFX**
Fixes #1338

### CODE REVIEW

**Comment by ndt93** [comment]
@SherryFX You have 2 commits with the same commit message. Can squash them into 1? And also rebase with the current master or merge if you are not familiar with rebasing yet.

**Comment by dariusf** [comment]
I think us linking to the workflow document is a bit of a mistake -- we renamed them at some point and didn't update the link. Maybe we could just link to the process document?

**Comment by damithc** [comment]
Yes, I agree with @dariusf 's comment.

**Comment by SherryFX** [comment]
@ndt93 Okay noted! Will amend that.
@dariusf @damithc Alright! So I will just remove the workflow link and rephrase the document such that it will only refer to developerGuide.md and process.md?

**Comment by ndt93** [comment]
@SherryFX When this PR is ready for review, you can make a comment here to let us know.

**Comment by SherryFX** [comment]
Hi all! This PR is ready for review now! Thanks!

**Comment by dariusf** [comment]
Hmm, thought you were going to remove the workflow link. Anyway, I think this needs very minimal changes. Something like 'check out the development process and open a pull request'.

**Comment by SherryFX** [comment]
@dariusf I have made the relevant changes. Is it alright now?

**Comment by dariusf** [comment]
Maybe we could keep it simple, and just have

```
Check out the [development process](...) and open a pull request!
```

Reason is that this is mainly for first-timers to read, so it should be concise, and probably doesn't need to mention PR-merging yet. :sweat_smile:

**Comment by SherryFX** [comment]
Okay noted! How about now?

**Comment by dariusf** [comment]
Thanks! It'd be good to squash like Thien said, because the overall change is quite minor.

**Comment by SherryFX** [comment]
@dariusf I am encountering a problem with squashing somehow. When I tried to `git rebase` my commits I will always get a list of commits from both the master branch and my branch. Moreover, my own commits are not grouped together so I could not simply squash them. Could you give me some advice on this problem? Thanks!

**Comment by damithc** [comment]
In the worst case, close this PR and open a new one.

**Comment by dariusf** [comment]
Don't worry about it, I'll squash this time.

**Comment by dariusf** [comment]
Merged in 0dba275026382a38d54b5823dc62b94471735f85.

**Comment by SherryFX** [comment]
Thank you! Apologies for the trouble! XD

**Pull request closed without merging**
