### PR TITLE
bView stops responding after alerts in window #484

### LINKED ISSUE #484: bView stops responding after alerts in window
to reproduce: try deleting a comment on an issue. Alert pops up for confirmation. HT throws an exception. is also tied to https://github.com/HubTurbo/HubTurbo/issues/471

### PR DESCRIPTION
**Pull request by rd1992**
fixed by catching the exception and updating chromedriver
Fixes #484

### CODE REVIEW

**Comment by damithc** [comment]
@dariusf am I supposed to get this new chromedriver when I run HT using the resources.jar?

**Comment by dariusf** [comment]
Yup, it's packaged in the jar. You might have to delete the existing `chromedriver.exe`, so the new one gets extracted.

**Comment by damithc** [comment]
How is it going to work for regular users? We don't have a way to ask them
to delete the exe file.

**Comment by dariusf** [comment]
A temporary measure could be to have HT remove it on startup. That's what we wanted to do for the cache files, in case the data model changed.

The long-term solution could be to improve the updater to the point where the chromedriver can been distributed separately (so only the 12mb~ jar file and right chromedriver per platform, not all 3, are downloaded). We could then update it separately as well.

**Pull request merged**
